### ISSUE TITLE
可以提供下s.yaml的简单配置吗？

### ISSUE THREAD

**Issue by nomango** [aliyun/fc-runtime-go-sdk#16]
之前用start-gin模板生成了一个代码，用的是在actions.pre-deploy中写好编译命令，然后用runtime=custom & customRuntimeConfig.command=./target/main 的方式启动

但当我使用这个sdk把main函数改掉后，会报错
```json
{
"ErrorCode":"CAExited",
"ErrorMessage":"The function either cannot be started or exited. ContainerStartDuration: 5 seconds.Function instance exited unexpected(code 1) with start command './target/main ' in 5.295 seconds.\nLogs:2022/07/22 10:52:37.884300 start http\r\n2022/07/22 10:52:37.884764 expected ali FC environment variables [FC_RUNTIME_API] are not defined"
}
```

想问下使用这个sdk后的 s.yaml 应该如何配置？

**Comment by fanzhe328** [comment]
如果runtime是custom的话，是不需要使用fc-runtime-go-sdk的SDK；这个SDK是提供给runtime为go1的。
如果要使用这个sdk，可以参考示例 https://github.com/awesome-fc/code-example/tree/master/golang/golang-oss

**Comment by nomango** [comment]
> 如果runtime是custom的话，是不需要使用fc-runtime-go-sdk的SDK；这个SDK是提供给runtime为go1的。 如果要使用这个sdk，可以参考示例 https://github.com/awesome-fc/code-example/tree/master/golang/golang-oss

谢谢，我按照这个配了下，报错
```json
{
"errorMessage":"Invalid handler 'main'",
"errorType":"FunctionUnhandledError: InvalidHandlerName","stackTrace":["InvalidHandlerName: Invalid handler 'main'"]
}
```

我的配置
```yaml
my-service:
  component: fc
  actions:
    pre-deploy:
      - run: GO111MODULE=on GOOS=linux CGO_ENABLED=0 go build -o main .
        path: ./cmd/fc
  props:
      service:
        # 省略...
      function:
        runetime: go1
        handler: main
        codeUri: './cmd/fc'
        # 省略...
```

还试了这个
```yaml
my-service:
  component: fc
  actions:
    pre-deploy:
      - run: GO111MODULE=on GOOS=linux CGO_ENABLED=0 go build -o target/main ./cmd/fc
        path: ./
  props:
      service:
        # 省略...
      function:
        runetime: go1
        handler: main
        codeUri: './target'
        # 省略...
```

报错是相同的，这个是什么原因呢？
